import React, { useEffect, useState } from "react";
import Head from "next/head";
import Checkbox from "../components/Checkbox";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AdminNavbar from "../components/AdminNavbar";
import { useRouter } from "next/router";

const DeleteCategory = () => {
  const [categoryTitle, setCategoryTitle] = useState("");
  const [loading, setLoading] = useState(false);
  const [disableButton, setDisableButton] = useState(false);

  const router = useRouter();

  const toastConfig = {
    position: "bottom-center",
    autoClose: 1000,
    hideProgressBar: true,
    closeOnClick: true,
    progress: undefined,
    theme: "dark",
    bodyClassName: "font-bold select-none font-Nunito",
    closeButton: false,
  };

  useEffect(() => {
    if (!localStorage.getItem("ADMIN_ACCESS")) {
      router.push("/admin");
    }
  }, []);

  const deleteCat = async (e) => {
    setLoading(true);
    setDisableButton(true);
    e.preventDefault();
    try {
      if (!categoryTitle) {
        toast.error("Enter the Title First", toastConfig);
        setLoading(false);
        setDisableButton(false);
        return;
      }

      const res = await fetch(`/api/rules/${categoryTitle}`, {
        method: "DELETE",
      });
      const result = await res.json();

      console.log(result);

      if (result.success === true) {
        toast.success("Successfully Delete !!", toastConfig);
        setLoading(false);
        setDisableButton(false);
      } else {
        toast.error("Not Deleted !!", toastConfig);
        setLoading(false);
        setDisableButton(false);
      }
    } catch (error) {
      console.log(error);
      toast.error("Not Deleted, Try Again some later", toastConfig);
      setLoading(false);
      setDisableButton(false);
    }
  };
  return (
    <>
      <Head>
        <title>MEET-IN : Delete Category</title>
        <meta
          name="description"
          content="Generated by developer for the who needs to be thier doubts and want to learn from the expert"
        />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <ToastContainer
        position="bottom-center"
        autoClose={3000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        theme="dark"
      />
      <div className="bg-purple-300 dark:bg-slate-600 w-[100vw] h-[100vh] transition-all duration-1000">
        <div className="fixed right-10 bottom-10">
          <Checkbox />
        </div>
        <div className="flex">
          <div className="bg-teal-300 transition-all duration-1000 h-[100vh] shadow-2xl p-10 dark:shadow-4xl dark:bg-slate-800">
            <AdminNavbar />
          </div>
          <div className="pl-[20rem] pt-[10rem]">
            <p className=" text-center text-4xl pt-10 font-bold text-white">
              DELETE THE CATEGORY
            </p>
            <form className="flex flex-col ">
              <div className="flex flex-col pt-20">
                <label htmlFor="title" className="text-xl text-white">
                  Enter the title of the Category
                </label>
                <input
                  type="text"
                  id="title"
                  placeholder="ex: Class 9 RBSE"
                  className="p-2 dark:bg-teal-800 outline-none text-black dark:placeholder:text-teal-300 placeholder:text-teal-900 bg-teal-100 transition-all w-96 duration-500 rounded ring-2 ring-teal-100 focus:ring-4 focus:ring-teal-500 mt-4"
                  onChange={(e) => {
                    setCategoryTitle(e.target.value);
                  }}
                  name="categoryTitle"
                  autoComplete="off"
                />
              </div>
              <div className="pt-20">
                <button
                  type="submit"
                  disabled={disableButton}
                  onClick={deleteCat}
                  className={` ${
                    disableButton
                      ? "cursor-not-allowed font-bold font-Crimson text-lg text-white bg-green-400 uppercase rounded  hover:bg-green-300  hover:text-green-500 transition-all duration-700 dark:text-white bg-transparent p-2 px-5 dark:bg-green-700 dark:hover:bg-green-900"
                      : "font-bold font-Crimson text-lg text-white bg-green-500 uppercase rounded  hover:bg-green-300  hover:text-green-500 transition-all duration-700 dark:text-white bg-transparent p-2 px-5 dark:bg-green-700 dark:hover:bg-green-900 cursor-pointer hover:shadow-3xl"
                  }`}
                >
                  {loading ? (
                    <img src="/admin.gif" className="w-[20px] h-[20px]" />
                  ) : (
                    "Delete"
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

export default DeleteCategory;
