import React from 'react'
import Head from 'next/head'

const about = (props) => {
    return (
        <>
            <Head>
                <title>MEET-IN - About</title>
                <meta name="description" content="Generated by developer for the who needs to be thier doubts and want to learn from the expert" />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <div className="container p-5  d-flex justify-content-center align-items-center flex-column mt-5">
                <p className={`fs-1 text-${props.mode === 'light' ? 'dark' : 'light'}`}>MEET OUR TEAM</p>
                <div className="container p-5">
                    <p className={`text-${props.mode === 'light' ? 'dark' : 'light'}`}>We are all very different. We Born in different cities and different places, at different times. But something is unites us all. It is knowledge. We all are gaining it from each and every seconds. But its time to evolve the pattern of getting knowledge. So we developed this website to which every student can get the best knowlwdge of his/her field. Student can solve their doubts to qualified teachers and can donate them for thier great work. We introduced a ranking system in each field and raise thier secondary income. The first ranked tutor will unlock the system of getting donation so that makes a competion among the teacher to be the best to get the number 1 position. At the end of the day we all are family.</p>
                </div>
                <div className="container mt-5">
                    <p className={`text-center text-uppercase fs-2 fw-bold text-${props.mode === 'light' ? 'dark' : 'light'}`}>
                        Developer's team
                    </p>

                    <div className="row row-cols-1 row-cols-md-4 g-4 mt-5">
                        <div className="col">
                            <div className={`card bg-${props.mode}`} style={{ width: "249px" }} >
                                <img src="/images/profile.png" className="card-img-top" alt="..." style={{ width: "245px" }} />
                                <div className={`card-body text-${props.mode === 'light' ? 'dark' : 'light'}`}>
                                    <h5 className="card-title">Group Member Name 1</h5>
                                    <p className="card-text">Some text about member 1</p>
                                </div>
                            </div>
                        </div>
                        <div className="col">
                            <div className={`card bg-${props.mode}`} style={{ width: "249px" }}>
                                <img src="/images/profile.png" className="card-img-top" alt="..." style={{ width: "245px" }} />
                                <div className={`card-body text-${props.mode === 'light' ? 'dark' : 'light'}`}>
                                    <h5 className="card-title">Group Member Name 2</h5>
                                    <p className="card-text">Some text about member 2</p>
                                </div>
                            </div>
                        </div>
                        <div className="col">
                            <div className={`card bg-${props.mode}`} style={{ width: "249px" }}>
                                <img src="/images/profile.png" className="card-img-top" alt="..." style={{ width: "245px" }} />
                                <div className={`card-body text-${props.mode === 'light' ? 'dark' : 'light'}`}>
                                    <h5 className="card-title">Group Member Name 3</h5>
                                    <p className="card-text">Some text about member 3</p>
                                </div>
                            </div>
                        </div>
                        <div className="col">
                            <div className={`card bg-${props.mode}`} style={{ width: "249px" }}>
                                <img src="/images/profile.png" className="card-img-top" alt="..." />
                                <div className={`card-body text-${props.mode === 'light' ? 'dark' : 'light'}`}>
                                    <h5 className="card-title">Group Member Name 4</h5>
                                    <p className="card-text">Some text about member 4</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="container mt-5">
                    <p className={`fs-2 fw-semibold text-center text-${props.mode === 'light' ? 'dark' : 'light'}`}>FACALITIES</p>
                    <div className="container text-center">
                        <div className="row">
                            <div className="col">
                                <img src="/images/teacher.png" alt="..." className={`img-thumbnail bg-${props.mode}`} />
                                <h2 className={`fs-4 mt-4 text-${props.mode === 'light' ? 'dark' : 'light'}`}> Teachers</h2>
                                <p className={`text-${props.mode === 'light' ? 'dark' : 'light'} mt-2`}>Teachers can connect with thier students by registering or login and try hard for getting the number 1 rank to unlock the donation system. If teacher is new to this website you have to first register youself and then you can teach your students.</p>
                            </div>
                            <div className="col">
                            <img src="/images/student.png" alt="..." className={`img-thumbnail bg-${props.mode}`} style={{width: '343px', height:"333px"}}/>
                            <h2 className={`fs-4 mt-4 text-${props.mode === 'light' ? 'dark' : 'light'}`}> Students</h2>
                                <p className={`text-${props.mode === 'light' ? 'dark' : 'light'} mt-2`}>Students can connect and gain the valuable knowledge according to their chosen category and can donate to thier favorite teacher. the students also have to register to tthis website if they are new to this site otherwise they simply can login.</p>
                            </div>
                            <div className="col">
                            <img src="/images/admin.png" alt="..." className={`img-thumbnail bg-${props.mode}`} style={{width: '343px', height:"333px"}}/>
                            <h2 className={`fs-4 mt-4 text-${props.mode === 'light' ? 'dark' : 'light'}`}> Admin</h2>
                                <p className={`text-${props.mode === 'light' ? 'dark' : 'light'} mt-2`}>Admin account can be access by the special id and password and can manage the teachers and students by removing them when necessary and can also manage and disturb the rating system by improving someone`s rating.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default about