import React from "react";
import IntroTeam from "./components/IntroTeam";
import Head from "next/head";
import styles from "../styles/About.module.css";
import Team from "./components/Team.jsx";

const about = (props) => {
  return (
    <>
      <Head>
        <title>MEET-IN : About</title>
        <meta
          name="description"
          content="Generated by developer for the who needs to be thier doubts and want to learn from the expert"
        />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <div className="bg-slate-100">
        <IntroTeam />
        <div className="container mt-5">
          <p
            className={`text-center text-uppercase fs-2 fw-bold text-${
              props.mode === "light" ? "dark" : "light"
            }`}
          >
            Developer's team
          </p>
          <Team />
        </div>
        <div className="container mt-5">
          <p
            className={`fs-2 fw-semibold text-center text-${
              props.mode === "light" ? "dark" : "light"
            }`}
          >
            FACALITIES
          </p>
          <div className="row">
            <div className="col-sm-6">
              <div className="card">
                <div
                  className="card-body"
                  style={{
                    backgroundColor: props.mode === "light" ? "white" : "black",
                    color: props.mode === "light" ? "black" : "white",
                  }}
                >
                  <img
                    src="/images/teacher.png"
                    className="img-fluid"
                    id={styles.imgTeacher}
                    alt="..."
                  />
                  <h5 className="card-title text-center mt-3">Teacher</h5>
                  <p className="card-text">
                    Teachers can connect with thier students by registering or
                    login and try hard for getting the number 1 rank to unlock
                    the donation system. If teacher is new to this website you
                    have to first register youself and then you can teach your
                    students.
                  </p>
                </div>
              </div>
            </div>
            <div className="col-sm-6 mb-4">
              <div className="card">
                <div
                  className="card-body"
                  style={{
                    backgroundColor: props.mode === "light" ? "white" : "black",
                    color: props.mode === "light" ? "black" : "white",
                  }}
                >
                  <img
                    src="/images/student.png"
                    className="img-fluid"
                    id={styles.imgStudent}
                    alt="..."
                  />
                  <h5 className="card-title text-center mt-3">Student</h5>
                  <p className="card-text">
                    Students can connect and gain the valuable knowledge
                    according to their chosen category and can donate to thier
                    favorite teacher. the students also have to register to
                    tthis website if they are new to this site otherwise they
                    simply can login.
                  </p>
                </div>
              </div>
            </div>
            <div className="col-sm-6">
              <div className="card">
                <div
                  className="card-body"
                  style={{
                    backgroundColor: props.mode === "light" ? "white" : "black",
                    color: props.mode === "light" ? "black" : "white",
                  }}
                >
                  <img
                    src="/images/admin.png"
                    className="img-fluid"
                    id={styles.imgAdmin}
                    alt="..."
                  />
                  <h5 className="card-title text-center mt-3">Admin</h5>
                  <p className="card-text">
                    Admin account can be access by the special id and password
                    and can manage the teachers and students by removing them
                    when necessary and can also manage and disturb the rating
                    system by improving someone`s rating.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default about;
