import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const contact = () => {

  const [user, setUser] = useState({
    name: "",
    phone: "",
    email: "",
    desc: "",
  });

  const [loader, setLoader] = useState(false);


  const toastConfig = {
    position: "bottom-center",
    autoClose: 1000,
    hideProgressBar: true,
    closeOnClick: true,
    progress: undefined,
    theme: "dark",
    bodyClassName: "font-bold select-none",
    closeButton: false
  }

  let name, value;

  const handleChange = (e) => {
    name = e.target.name;
    value = e.target.value;

    setUser({ ...user, [name]: value });
  };

  const PostData = async (e) => {
    e.preventDefault();
    setLoader(true);
    const { name, phone, email, desc } = user;

    if (!name || !phone || !email || !desc) {
      window.scrollTo(0, 0);
      toast.warning("Please Fill all the fields", toastConfig);
        setLoader(false);        
    }else {
      const res = await fetch("/api/app", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name,
          phone,
          email,
          desc,
        }),
      });

      const data = await res.json();
      if (data.status === 422 || !data) {
        toast.error("Error Occured Try Again Later !!", toastConfig);
        setLoader(false);
        setUser({ name: "", phone: "", email: "", desc: "" });
        window.scrollTo(0, 0);
      } else {
        window.scrollTo(0, 0);
        toast.success("Thank You For Contacting US !!", toastConfig);
        setLoader(false);

        setUser({ name: "", phone: "", email: "", desc: "" });
      }
    }
  };
  return (
    <>
      <Head>
        <title>GURU COOL : Contact Us</title>
        <meta
          name="description"
          content="Generated by developer for the who needs to be thier doubts and want to learn from the expert"
        />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <ToastContainer
        position="bottom-center"
        autoClose={1000}
        hideProgressBar={true}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        theme="dark"
      />
      <div className={"antialiased dark:bg-slate-600 bg-gray-100 h-full transition-all duration-1000"} data-aos="fade-out">
        <div className="flex w-full min-h-screen justify-center items-center ">
          <div
            className={
              "flex  md:flex-row md:space-x-6 md:space-y-0 flex-col space-y-6 bg-cyan-700 w-full max-w-4xl p-8 sm:p-12 rounded-xl shadow-lg overflow-hidden text-white"
            }
          >
            <div className="flex flex-col space-y-8 justify-between">
              <div>
                <h1 className="font-bold text-4xl tracking-wide select-none  ">
                  Contact Us
                </h1>
                <p className="pt-2 text-cyan-100 text-sm select-none">
                  We will soon contact you once you send your information to us
                  and clearly tell your problem in the concern section
                </p>
              </div>
              <div className="flex flex-col space-y-6 select-none">
                <div className="inline-flex space-x-2 items-center">
                  <i className="fa-solid fa-phone text-teal-300 text-xl"></i>
                  <span>(+91) XXXXXXXXXX</span>
                </div>
                <div className="inline-flex space-x-2 items-center">
                  <i className="fa-solid fa-envelope text-teal-300 text-xl"></i>
                  <span> vbpc1956@gmail.com</span>
                </div>
                <div className="inline-flex space-x-2 items-center">
                  <i className="fa-solid fa-location-dot text-teal-300 text-xl"></i>
                  <span>vidya bhawan polythecnic college Udaipur</span>
                </div>
              </div>
              <div className="flex space-x-4 text-lg ">
                <Link href={"https://www.facebook.com/groups/573143149428004/"}>
                  <i className="fa-brands fa-facebook hover:bg-blue-500"></i>
                </Link>
                <Link
                  href={"https://www.instagram.com/vidya.bhawanpolycollegeudr/"}
                >
                  <i className="fa-brands fa-instagram"></i>
                </Link>
                <Link
                  href={
                    "https://www.youtube.com/channel/UCoXFg-xFi-nqBOZHgFIf-kQ"
                  }
                >
                  <i className="fa-brands fa-youtube"></i>
                </Link>
              </div>
            </div>
            <div className="relative select-none">
              <div className="absolute z-10 w-40 h-40 bg-teal-400 rounded-full -right-28 -top-28"></div>
              <div className="absolute z-10 w-40 h-40 bg-teal-400 rounded-full -left-28 -bottom-16"></div>
              <div className="relative z-10 bg-white dark:bg-slate-600 rounded-xl shadow-lg p-8 text-gray-700 md:w-96">
                <form method="POST" className="flex flex-col space-y-4">
                  <div>
                    <label htmlFor="" className="dark:text-white text-sm">
                      Your Name
                    </label>
                    <input
                      type="text"
                      className="ring-1 ring-gray-300 w-full dark:text-white rounded-md px-4 py-2 mt-2 outline-none focus:ring-2 focus:ring-teal-300"
                      placeholder="Name Here"
                      name="name"
                      value={user.name}
                      onChange={handleChange}
                      autoComplete="off"
                    />
                  </div>

                  <div>
                    <label htmlFor="" className="dark:text-white text-sm">
                      Your Phone
                    </label>
                    <input
                      type="number"
                      className="ring-1 ring-gray-300 w-full dark:text-white dark:bg-dark-800 rounded-md px-4 mt-2 py-2 outline-none focus:ring-2 focus:ring-teal-300"
                      placeholder="Phone Number"
                      name="phone"
                      value={user.phone}
                      onChange={handleChange}
                      autoComplete="off"
                    />
                  </div>
                  <div>
                    <label htmlFor="" className="dark:text-white text-sm">
                      Your Email
                    </label>
                    <input
                      type="email"
                      className="ring-1 ring-gray-300 dark:text-white w-full rounded-md px-4 py-2 mt-2 outline-none focus:ring-2 focus:ring-teal-300"
                      placeholder="name@example.com"
                      name="email"
                      value={user.email}
                      onChange={handleChange}
                      autoComplete="off"
                    />
                  </div>
                  <div>
                    <label htmlFor="" className="dark:text-white text-sm">
                      Write Your Concern here
                    </label>
                    <textarea
                      className="ring-1 ring-gray-300 w-full dark:text-white rounded-md px-4 py-2 mt-2 outline-none focus:ring-2 focus:ring-teal-300"
                      placeholder="Leave a comment here"
                      name="desc"
                      value={user.desc}
                      rows="4"
                      onChange={handleChange}
                      autoComplete="off"
                    />
                  </div>
                  <button
                    className={`dark:text-white w-[11rem] flex items-center justify-center transition-all duration-500 hover:shadow-3xl cursor-pointer self-end bg-cyan-700   pt-3  text-white font-bold rounded-lg px-6 py-2 uppercase text-sm`}
                    type="submit"
                    name="send"
                    onClick={PostData}
                  > {loader  ? <img src="/adminIdPass.gif" alt="..." className="w-[20px] h-[20px]"/> :"Send Message"}</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default contact;
