import React, { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/contact.module.css'
import Alert from './Alert'
const contact = (props) => {
    const [alert, setAlert] = useState(null)
    const showAlert = (message, type) =>{
        setAlert({
            msg: message,
            type: type
        })
        setTimeout(()=>{
            setAlert(null)
        },2000)
    } 


    const [user, setUser] = useState({
        name: "", phone: "", email: "", desc: ""
    });

    let name, value;

    const handleChange = (e) => {
        name = e.target.name;
        value = e.target.value;

        setUser({ ...user, [name]: value })
    }

    const PostData = async (e) => {
        e.preventDefault();
        const { name, phone, email, desc } = user;

        if(!name || !phone || !email || !desc){
-           showAlert("Not Send, Please Fill all the fields", "danger");
        }else{
            const res = await fetch("/api/app", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    name, phone, email, desc
                })
            });
    
            const data = await res.json();
            if (data.status === 422 || !data) {
                showAlert("Not Send, Please try Again Later", "danger")
            } else {
                showAlert("Sent, Thank You for Contacting Us", "success")
            }
        }

    }
    return (
        <>
            <Head>
                <title>MEET-IN : Contact Us</title>
                <meta name="description" content="Generated by developer for the who needs to be thier doubts and want to learn from the expert" />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <Alert alert= {alert}/>
            <div className={`container mt-5 d-flex mb-5`}>
                <div className={`container-fluid shadow p-5 mb-5 rounded bg-${props.mode} `}>
                    <p className={`fs-2 fw-bold text-${props.mode ==='light' ?'dark':'light'}`}>Get In Touch</p>
                    <form method='POST'>
                        <div className="form-floating mb-3">
                            <input type="text" className="form-control" id="floatingInput" placeholder="Name Here" name='name' value={user.name} onChange={handleChange} autoComplete='off' />
                            <label htmlFor="floatingInput">Name</label>
                        </div>
                        <div className="form-floating mb-3">
                            <input type="number" className="form-control" id="floatingPassword" placeholder="Phone Number" name='phone' value={user.phone} onChange={handleChange} autoComplete='off' />
                            <label htmlFor="floatingPassword"> Phone</label>
                        </div>
                        <div className="form-floating mb-3">
                            <input type="email" className="form-control" id="floatingInput" placeholder="name@example.com" name='email' value={user.email} onChange={handleChange} autoComplete='off' />
                            <label htmlFor="floatingInput">Email </label>
                        </div>
                        <div className="form-floating">
                            <textarea className="form-control" placeholder="Leave a comment here" id="floatingTextarea2" name='desc' value={user.desc} onChange={handleChange} autoComplete='off' />
                            <label htmlFor="floatingTextarea2">Write Your Concern here</label>
                        </div>
                        <input className="btn btn-success mt-5 d-block m-auto" id={styles.button} type='submit' name='send' value='Send' onClick={PostData} />
                    </form>
                </div>
                <div className="text-bg-primary p-3 fs-1 fw-bold container text-center ">
                    <p>Contact Us </p>
                    <div className="d-flex mt-5 ms-2">
                        <img src="/images/address.png" alt="..." id={styles.img} className="img-fluid" />
                        <div className="fw-bold fs-5 ms-1 mt-1">
                            Address:
                        </div>
                        <Link href={'https://goo.gl/maps/NM75qDEK4yR4xz5h9'} id={styles.link}>
                            <div className="ms-1 fs-5 mt-1 fw-light"> 185, Vidya Bhawan Polythecnic College, Udaipur, Raj. </div>
                        </Link>
                    </div>
                    <div className="d-flex ms-3" id={styles.margin}>
                        <img src="/images/phone.png" alt="..." id={styles.img2} className="img-fluid" />
                        <div className="fw-bold fs-5 ms-2 mt-1">
                            Phone:
                        </div>
                        <div className="ms-2 fs-5 mt-1 fw-light">6350330324</div>
                    </div>
                    <div className="d-flex ms-3" id={styles.margin}>
                        <img src="/images/tele.png" alt="..." id={styles.img2} className="img-fluid" />
                        <div className="fw-bold fs-5 ms-2 mt-1">
                            Email:
                        </div>
                        <div className="ms-2 fs-5 mt-1 fw-light">vaibhavmali537@gmail.com </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default contact