import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import Alert from "./components/Alert";
const contact = () => {
  const [alert, setAlert] = useState(null);
  const showAlert = (message, type, color) => {
    setAlert({
      msg: message,
      type: type,
      color:color
    });

    setTimeout(() => {
      setAlert(null);
    }, 2000);
  };
  const [user, setUser] = useState({
    name: "",
    phone: "",
    email: "",
    desc: "",
  });

  let name, value;

  const handleChange = (e) => {
    name = e.target.name;
    value = e.target.value;

    setUser({ ...user, [name]: value });
  };

  const PostData = async (e) => {
    e.preventDefault();
    const { name, phone, email, desc } = user;

    if (!name || !phone || !email || !desc) {
      window.scrollTo(0, 0)
      showAlert("Not Send, Please Fill all the fields", "Error", "red");
    } else {
      const res = await fetch("/api/app", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name,
          phone,
          email,
          desc,
        }),
      });

      const data = await res.json();
      if (data.status === 422 || !data) {
        showAlert("Not Send, Please try Again Later", "Error","red");
          window.scrollTo(0, 0)
        // window.alert("Sent")
      } else {
        window.scrollTo(0, 0)
        showAlert("Sent, Thank You for Contacting Us", "Success","green");
        // window.alert(" NO Sent")
      }
    }
  };
  return (
    <>
      <Head>
        <title>MEET-IN : Contact Us</title>
        <meta
          name="description"
          content="Generated by developer for the who needs to be thier doubts and want to learn from the expert"
        />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <Alert alert={alert} />
      <div className={"antialiased dark:bg-slate-600 bg-gray-100 h-full"}>
        <div className="flex w-full min-h-screen justify-center items-center ">
          <div
            className={
              "flex  md:flex-row md:space-x-6 md:space-y-0 flex-col space-y-6 bg-cyan-700 w-full max-w-4xl p-8 sm:p-12 rounded-xl shadow-lg overflow-hidden text-white"
            }
          >
            <div className="flex flex-col space-y-8 justify-between">
              <div>
                <h1 className="font-bold text-4xl tracking-wide ">
                  Contact Us
                </h1>
                <p className="pt-2 text-cyan-100 text-sm">
                  We will soon contact you once you send your information to us
                  and clearly tell your problem in the concern section
                </p>
              </div>
              <div className="flex flex-col space-y-6">
                <div className="inline-flex space-x-2 items-center">
                  <i className="fa-solid fa-phone text-teal-300 text-xl"></i>
                  <span>(+91) 635330324</span>
                </div>
                <div className="inline-flex space-x-2 items-center">
                  <i class="fa-solid fa-envelope text-teal-300 text-xl"></i>
                  <span> vbpc1956@gmail.com</span>
                </div>
                <div className="inline-flex space-x-2 items-center">
                  <i class="fa-solid fa-location-dot text-teal-300 text-xl"></i>
                  <span>vidya bhawan polythecnic college Udaipur</span>
                </div>
              </div>
              <div className="flex space-x-4 text-lg ">
                <Link href={"https://www.facebook.com/groups/573143149428004/"}>
                  <i className="fa-brands fa-facebook"></i>
                </Link>
                <Link
                  href={"https://www.instagram.com/vidya.bhawanpolycollegeudr/"}
                >
                  <i className="fa-brands fa-instagram"></i>
                </Link>
                <Link
                  href={
                    "https://www.youtube.com/channel/UCoXFg-xFi-nqBOZHgFIf-kQ"
                  }
                >
                  <i className="fa-brands fa-youtube"></i>
                </Link>
              </div>
            </div>
            <div className="relative">
              <div className="absolute z-10 w-40 h-40 bg-teal-400 rounded-full -right-28 -top-28"></div>
              <div className="absolute z-10 w-40 h-40 bg-teal-400 rounded-full -left-28 -bottom-16"></div>
              <div className="relative z-10 bg-white dark:bg-slate-600 rounded-xl shadow-lg p-8 text-gray-700 md:w-96">
                <form method="POST" className="flex flex-col space-y-4">
                  <div>
                    <label htmlFor="" className="dark:text-white text-sm">
                      Your Name
                    </label>
                    <input
                      type="text"
                      className="ring-1 ring-gray-300 w-full dark:text-white rounded-md px-4 py-2 mt-2 outline-none focus:ring-2 focus:ring-teal-300"
                      placeholder="Name Here"
                      name="name"
                      value={user.name}
                      onChange={handleChange}
                      autoComplete="off"
                    />
                  </div>

                  <div>
                    <label htmlFor="" className="dark:text-white text-sm">
                      Your Phone
                    </label>
                    <input
                      type="number"
                      className="ring-1 ring-gray-300 w-full dark:text-white dark:bg-dark-800 rounded-md px-4 mt-2 py-2 outline-none focus:ring-2 focus:ring-teal-300"
                      placeholder="Phone Number"
                      name="phone"
                      value={user.phone}
                      onChange={handleChange}
                      autoComplete="off"
                    />
                  </div>
                  <div>
                    <label htmlFor="" className="dark:text-white text-sm">
                      Your Email
                    </label>
                    <input
                      type="email"
                      className="ring-1 ring-gray-300 dark:text-white w-full rounded-md px-4 py-2 mt-2 outline-none focus:ring-2 focus:ring-teal-300"
                      placeholder="name@example.com"
                      name="email"
                      value={user.email}
                      onChange={handleChange}
                      autoComplete="off"
                    />
                  </div>
                  <div>
                    <label htmlFor="" className="dark:text-white text-sm">
                      Write Your Concern here
                    </label>
                    <textarea
                      className="ring-1 ring-gray-300 w-full dark:text-white rounded-md px-4 py-2 mt-2 outline-none focus:ring-2 focus:ring-teal-300"
                      placeholder="Leave a comment here"
                      name="desc"
                      value={user.desc}
                      rows="4"
                      onChange={handleChange}
                      autoComplete="off"
                    />
                  </div>
                  <input
                    className="inline-block dark:text-white cursor-pointer self-end bg-cyan-700   pt-3  text-white font-bold rounded-lg px-6 py-2 uppercase text-sm"
                    type="submit"
                    name="send"
                    value="Send Message"
                    onClick={PostData}
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default contact;
