import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>MEET-IN</title>
        <meta name="description" content="Generated by developer for the who needs to be thier doubts and want to learn from the expert" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
    </>
  )
}
