import { useRouter } from "next/router";
import React, { useCallback, useEffect, useState } from "react";
import { useSocket } from "./context/SocketProvider";
import Head from "next/head";

const lobby = () => {
  const [email, setEmail] = useState("");
  const [room, setRoom] = useState("");

  const router = useRouter();

  const socket = useSocket();

  const handleSubmitForm = useCallback(
    (e) => {
      e.preventDefault();
      socket.emit("room:join", { email, room });
    },
    [email, room, socket]
  );

  const handleJoinRoom = useCallback(
    (data) => {
      const { email, room } = data;
      router.push(`/room/${room}`);
    },
    [router]
  );

  useEffect(() => {
    socket.on("room:join", handleJoinRoom);
    return () => socket.off("room:join", handleJoinRoom);
  }, [socket, handleJoinRoom]);
  return (
    <>
      <Head>
        <title>GURU COOL : LOBBY</title>
        <meta
          name="description"
          content="Generated by developer for the who needs to be thier doubts and want to learn from the expert"
        />
        <link rel="icon" href="/images/logo.png" />
      </Head>
    <div className="text-black flex items-center justify-center flex-col">
      <h1 className="text-7xl my-36">Lobby</h1>
      <form onSubmit={handleSubmitForm} className="flex flex-col">
        <label htmlFor="email" className="text-3xl">Email ID : </label>
        <input
          type="email"
          className="my-5 w-96 outline-none  ring-2 ring-black focus:ring-4 p-1 text-lg transition-all duration-500 rounded"
          id="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          autoComplete="off"
        />
        <label htmlFor="room" className="text-3xl">ROOM NUMBER : </label>
        <input
          type="text"
          className="my-5 w-96 outline-none  ring-2 ring-black focus:ring-4 p-1 text-lg transition-all duration-500 rounded"
          id="room"
          value={room}
          onChange={(e) => setRoom(e.target.value)}
        />
        <button className="">Join</button>
      </form>
    </div>
    </>
  );
};

export default lobby;
