import React from 'react'
import Head from 'next/head'

const login = () => {
    return (
        <>
            <Head>
                <title>MEET-IN : Login</title>
                <meta name="description" content="Generated by developer for the who needs to be thier doubts and want to learn from the expert" />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <div className='dark:bg-slate-600 dark:text-white bg-slate-100'>This is the login page</div>
        </>
    )
}

export default login