import React from 'react'
import Head from 'next/head'

const Register = (props) => {
  return (
    <>
      <Head>
        <title>MEET-IN - Registation</title>
        <meta name="description" content="Generated by developer for the who needs to be thier doubts and want to learn from the expert" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <p className={`fs-1 text-center text-${props.mode === 'light' ? 'dark' : 'light'} mt-5 pt-5`}>Register to MEET-IN </p>
      <div className="container d-flex justify-content-center align-items-center p-5">
        <div className={`bg-success text-${props.mode === 'light' ? 'dark' : 'light'}`}>
          Hello
        </div>
        <div className={`bg-primary text-${props.mode === 'light' ? 'dark' : 'light'}`}>
          Hello
        </div>
      </div>
    </>
  )
}

export default Register