import React from 'react'
import Head from 'next/head'

const Register = () => {
  return (
    <>
      <Head>
        <title>Educative - Registation</title>
        <meta name="description" content="Generated by developer for the who needs to be thier doubts and want to learn from the expert" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      This is Register Page
    </>
  )
}

export default Register